import Foundation

// AUTO-GENERATED by tools/library/gen_seeds.py. Do not edit by hand.
// A tiny offline taster: one pattern per category. The full library
// ships as a bundled asset (library.json) and refreshes over the network.
enum SeedPatterns {

    static let tile: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "lemon", name: "Lemon", hex: "#FFF44F"), PaletteColor(id: "hot_pink", name: "Hot Pink", hex: "#FF1493"), PaletteColor(id: "purple", name: "Purple", hex: "#800080")]
        let rows: [String] = ["............................", ".............00.............", ".............22.............", "............0220............", "...........021120...........", "...........221122...........", "..........02100120..........", "..........21100112..........", ".........0210220120.........", ".........2100220012.........", "........021021120120........", ".......02102211220120.......", ".......22102100120122.......", "......0210211001120120......", "......2110210000120112......", ".....021021111111120120.....", "....02100222222222200120....", "....22102222222222220122....", "...0210000000000000000120...", "...2111111111111111111112...", "..022222222222222222222220..", "............................", "............................", "............................", "............................", "............................", "............................", "............................"]
        return FusePattern(
            id: "geometric-fa04b9d6-6352-5d2f-84b8-64ba72511aee", title: "Concentric 3-gon t2",
            category: .geometric, createdBy: .system,
            grid: GridSize(width: 28, height: 28),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .medium, tags: ["concentric", "geometric"],
            version: 1
        )
    }()

    static let mandala: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "yellow", name: "Yellow", hex: "#F5D000"), PaletteColor(id: "orange", name: "Orange", hex: "#FF8C00"), PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "purple", name: "Purple", hex: "#800080")]
        let rows: [String] = ["........................", ".........333333.........", "......333..00..333......", ".....33....00....33.....", "....33............33....", "...33.....1111.....33...", "..330..111....111..033..", "..300..............003..", "..30.111........111.03..", ".3....1...2..2...1....3.", ".3.........112........3.", ".3..111...1001...111..3.", ".3..111.22100122.111..3.", ".3.........112........3.", ".3....1...2..2...1....3.", "..30.111........111.03..", "..300..............003..", "..330..111....111..033..", "...33.....1111.....33...", "....33............33....", ".....33....00....33.....", "......333..00..333......", ".........333333.........", "........................"]
        return FusePattern(
            id: "mandalas-f525366d-665f-5afb-9fc7-f3f35ae9a433", title: "Mandala 6-fold 181",
            category: .mandalas, createdBy: .system,
            grid: GridSize(width: 24, height: 24),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .medium, tags: ["mandala", "6fold", "mandalas"],
            version: 1
        )
    }()

    static let heart: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "red", name: "Red", hex: "#CC1122")]
        let rows: [String] = ["...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "...0000.000000000000.0000..", "...0000000000000000000000..", "...0000000000000000000000..", "...0000000000000000000000..", "....000000.000000.000000...", ".....0000...0000...0000....", "......00.....00.....00.....", "...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "...........................", "..........................."]
        return FusePattern(
            id: "hearts-3b62f20d-d27d-5f4c-a229-38534ce1804d", title: "Heart Trio Row",
            category: .hearts, createdBy: .system,
            grid: GridSize(width: 27, height: 27),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .medium, tags: ["heart", "row", "hearts"],
            version: 1
        )
    }()

    static let star: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "orange", name: "Orange", hex: "#FF8C00"), PaletteColor(id: "cheddar", name: "Cheddar", hex: "#FF9900")]
        let rows: [String] = ["...........................", "...........................", ".............0.............", "............000............", "............000............", "............0.0............", "...........................", "...........................", "...........................", "....0........1........0....", "...000.......1.......000...", "....00......111......00....", "...0.....111111111.....0...", "...........11111...........", "...........11111...........", "...........11111...........", "...........1...1...........", "...........................", "...........................", "........0.........0........", "......0000.......0000......", ".......00.........00.......", "...........................", "...........................", "...........................", "...........................", "..........................."]
        return FusePattern(
            id: "stars-9a35a3dc-d370-56b5-84c1-3ea91c493a4a", title: "Star Wreath 5",
            category: .stars, createdBy: .system,
            grid: GridSize(width: 27, height: 27),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .easy, tags: ["star", "wreath", "stars"],
            version: 1
        )
    }()

    static let flower: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "yellow", name: "Yellow", hex: "#F5D000"), PaletteColor(id: "cheddar", name: "Cheddar", hex: "#FF9900"), PaletteColor(id: "dark_brown", name: "Dark Brown", hex: "#4B2C20")]
        let rows: [String] = [".............................", ".............................", ".............000.............", ".........000.000.000.........", ".........00000100000.........", "......00.010.111.010.00......", ".....0000111111111110000.....", ".....0001111.111.1111000.....", "......010111.....111010......", "...000111....222....111000...", "...001111..2222222..111100...", "...000111.222222222.111000...", "....0.1...222222222...1.0....", "..000111.22222222222.111000..", "..001111.22222222222.111100..", "..000111.22222222222.111000..", "....0.1...222222222...1.0....", "...000111.222222222.111000...", "...001111..2222222..111100...", "...000111....222....111000...", "......010111.....111010......", ".....0001111.111.1111000.....", ".....0000111111111110000.....", "......00.010.111.010.00......", ".........00000100000.........", ".........000.000.000.........", ".............000.............", ".............................", "............................."]
        return FusePattern(
            id: "flowers-840bcef7-7490-518a-867d-b25d5f5921df", title: "Sunflower 1",
            category: .flowers, createdBy: .system,
            grid: GridSize(width: 29, height: 29),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["flower", "sunflower"],
            version: 1
        )
    }()

    static let rainbow: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "white", name: "White", hex: "#FFFFFF"), PaletteColor(id: "yellow", name: "Yellow", hex: "#F5D000"), PaletteColor(id: "orange", name: "Orange", hex: "#FF8C00"), PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "purple", name: "Purple", hex: "#800080"), PaletteColor(id: "blue", name: "Blue", hex: "#1553B0"), PaletteColor(id: "dark_blue", name: "Dark Blue", hex: "#00008B"), PaletteColor(id: "green", name: "Green", hex: "#2E8B57")]
        let rows: [String] = ["00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000000000000000000000", "00000000000033333000000000000", "00000000033333333333000000000", "00000003332222222223330000000", "00000033222221112222233000000", "00000332221111111112223300000", "00003322111177777111122330000", "00033221117777777771112233000", "00032211777555555577711223000", "00332211775556665557711223300", "00322117755666666655771122300", "00322117556644444665571122300", "00022177556444044465577122000", "00001177566440004466577110000", "00000177566400000466577100000", "00000000000000000000000000000"]
        return FusePattern(
            id: "rainbows-c2f324e0-79cd-573c-82a8-be0abc32bc3a", title: "Rainbow Arc 1",
            category: .rainbows, createdBy: .system,
            grid: GridSize(width: 29, height: 29),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["rainbow", "arc"],
            version: 1
        )
    }()

    static let rocket: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "white", name: "White", hex: "#FFFFFF"), PaletteColor(id: "yellow", name: "Yellow", hex: "#F5D000"), PaletteColor(id: "lemon", name: "Lemon", hex: "#FFF44F"), PaletteColor(id: "orange", name: "Orange", hex: "#FF8C00"), PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "sky_blue", name: "Sky Blue", hex: "#5BC8F5"), PaletteColor(id: "navy", name: "Navy", hex: "#001F5B")]
        let rows: [String] = ["66666666666666666666666662666", "66666666666666665666666666666", "66666666066666466666666666666", "66666666666666466666666666666", "66666666666664446666666626666", "66666666666664446666066666666", "66666666666644444666666666666", "66666666666644444666666666666", "66666666666444444466666666666", "66666666666600000666666666666", "66666666666600000666666666666", "66666666666005550066666666666", "66666666666005550066666666666", "66666666666005550066666666666", "66666666666000000066666666666", "66666666666000000066666666666", "66666606665000000066666666666", "66666666666000000066666666666", "66666666666000000066666666666", "66666666664000000646666666666", "66666666644600000644666666666", "66666666444600000644466666666", "66666666444660006644466666566", "66666666666666066666666666666", "66666666666661116666666666666", "66666666666663136666666666666", "66660666666263136666666666666", "66666666666666366666666666666", "66666666666666366666666666666"]
        return FusePattern(
            id: "space-e26a9e16-4751-5058-aa7a-261d1bb29006", title: "Rocket 2",
            category: .space, createdBy: .system,
            grid: GridSize(width: 29, height: 29),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["space", "rocket"],
            version: 1
        )
    }()

    static let smiley: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "yellow", name: "Yellow", hex: "#F5D000"), PaletteColor(id: "black", name: "Black", hex: "#000000")]
        let rows: [String] = ["..........................", "...........0000...........", "........0000000000........", "......00000000000000......", ".....0000000000000000.....", "....000000000000000000....", "...00000000000000000000...", "...00000000000000000000...", "..0000000000000000000000..", "..0000000000000000000000..", "..0000011100000011100000..", ".000000111000000111000000.", ".000000111000000111000000.", ".000000000000000000000000.", ".000000000000000000000000.", "..0000000000000000000000..", "..0000000000000000000000..", "..0000001100000011000000..", "...00000111000011100000...", "...00000001111110000000...", "....000000011110000000....", ".....0000000000000000.....", "......00000000000000......", "........0000000000........", "...........0000...........", ".........................."]
        return FusePattern(
            id: "emoji-cf8aea84-26a1-5bdb-8c46-d606f8edf9c4", title: "Happy Smile",
            category: .emoji, createdBy: .system,
            grid: GridSize(width: 26, height: 26),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["emoji", "face", "happy"],
            version: 1
        )
    }()

    static let gem: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "purple", name: "Purple", hex: "#800080"), PaletteColor(id: "blue", name: "Blue", hex: "#1553B0"), PaletteColor(id: "dark_blue", name: "Dark Blue", hex: "#00008B"), PaletteColor(id: "aqua", name: "Aqua", hex: "#00FFFF")]
        let rows: [String] = ["........................", "........................", "...........22...........", "...........22...........", "...........22...........", "...........22...........", "...........22...........", "........................", "...........00...........", "...........00...........", "..........0000..........", "..........0000..........", "..........0000..........", ".....3....0000....1.....", ".....33....00....11.....", "....333....00....111....", ".....33..........11.....", ".....33..........11.....", ".....3............1.....", "........................", "........................", "........................", "........................", "........................"]
        return FusePattern(
            id: "gems-e691f989-7692-561d-89d4-562822ff85ef", title: "Marquise Cluster 3",
            category: .gems, createdBy: .system,
            grid: GridSize(width: 24, height: 24),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .easy, tags: ["gem", "cluster", "gems"],
            version: 1
        )
    }()

    static let letter: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "black", name: "Black", hex: "#000000")]
        let rows: [String] = [".......", "..000..", ".0...0.", ".0...0.", ".00000.", ".0...0.", ".0...0.", ".0...0.", "......."]
        return FusePattern(
            id: "icon-b214173a-8119-5d1e-bc9f-defec6d56a88", title: "Letter A",
            category: .icons, createdBy: .system,
            grid: GridSize(width: 7, height: 9),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .easy, tags: ["letter", "a", "text", "alphabet"],
            version: 1
        )
    }()

    static let animals: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "orange", name: "Orange", hex: "#FF8C00"), PaletteColor(id: "pink", name: "Pink", hex: "#FF69B4"), PaletteColor(id: "light_blue", name: "Light Blue", hex: "#87CEEB"), PaletteColor(id: "dark_brown", name: "Dark Brown", hex: "#4B2C20"), PaletteColor(id: "dark_gray", name: "Dark Gray", hex: "#444444")]
        let rows: [String] = ["22222222222222222222222222", "22222222222222222222222222", "22222002222222222220022222", "22222002200000000220022222", "22222110000000000001122222", "22220110000000000001102222", "22220110000000000001102222", "22200000000000000000000222", "22200000000000000000000222", "22200000000000000000000222", "22200000000000000000000222", "22200000000000000000000222", "22200000000000000000000222", "22200000000000000000000222", "22244400000011000000444222", "22200044400011000444000222", "22200044400031000444000222", "22244400000030000000444222", "22220000000030000000002222", "22222000000000000000022222", "22222200000000000000222222", "22222220000000000002222222", "22222222200000000222222222", "22222222222222222222222222", "22222222222222222222222222", "22222222222222222222222222"]
        return FusePattern(
            id: "animals-8c3f8ac4-770b-58c8-902a-92bcadc6e299", title: "Cat 1",
            category: .animals, createdBy: .system,
            grid: GridSize(width: 26, height: 26),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["animal", "cat", "cute"],
            version: 1
        )
    }()

    static let birds: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "white", name: "White", hex: "#FFFFFF"), PaletteColor(id: "orange", name: "Orange", hex: "#FF8C00"), PaletteColor(id: "light_blue", name: "Light Blue", hex: "#87CEEB"), PaletteColor(id: "brown", name: "Brown", hex: "#8B5E3C"), PaletteColor(id: "dark_brown", name: "Dark Brown", hex: "#4B2C20"), PaletteColor(id: "black", name: "Black", hex: "#000000")]
        let rows: [String] = ["22222222222222222222222222", "22222222222222222222222222", "22222222222222222222222222", "22222222222222222222222222", "22222222222222222222222222", "22222222222333322222222222", "22222222223330332222222222", "22222222223333532222222222", "22222222223333331111222222", "22222222233333332222222222", "22222222334433332222222222", "22222222334443333222222222", "22222222344444333222222222", "22222223344444333322222222", "22222223344444333322222222", "22222223344444333322222222", "22222223344444333222222222", "22222333344444333222222222", "22223333334443333222222222", "22222333233333332222222222", "22222222223333322222222222", "22222222222232222222222222", "22222222222222221222222222", "22222222222222222222222222", "22222222222222222222222222", "22222222222222222222222222"]
        return FusePattern(
            id: "birds-44be6d48-a0a8-5e10-9b7a-3b7de8d656a3", title: "Robin 1",
            category: .birds, createdBy: .system,
            grid: GridSize(width: 26, height: 26),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["bird", "robin"],
            version: 1
        )
    }()

    static let fish: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "white", name: "White", hex: "#FFFFFF"), PaletteColor(id: "orange", name: "Orange", hex: "#FF8C00"), PaletteColor(id: "pumpkin", name: "Pumpkin", hex: "#FF6600"), PaletteColor(id: "navy", name: "Navy", hex: "#001F5B"), PaletteColor(id: "toothpaste", name: "Toothpaste", hex: "#B2FFFF"), PaletteColor(id: "black", name: "Black", hex: "#000000"), PaletteColor(id: "dark_gray", name: "Dark Gray", hex: "#444444")]
        let rows: [String] = ["333333333333333333333333", "333333333333333333333333", "333333333333333333333333", "333333333333333333333333", "333333333333333333333333", "334433333333233333333333", "334433333332223333333333", "333333333122223333333333", "333333111111111133333333", "333331111111111113333133", "333311051111111111311133", "333311001111111111111133", "333366111111111111111133", "333311111111111111311133", "333331111111111113333133", "333333111111111133333333", "333333333111113333333333", "333333333333333333333333", "333333333333333333333333", "333333333333333333333333", "333333333333333333333333", "333333333333333333333333", "333333333333333333333333", "333333333333333333333333"]
        return FusePattern(
            id: "fish-cab85919-f2b5-56b2-a4d4-0504aff22815", title: "Fish 1",
            category: .fish, createdBy: .system,
            grid: GridSize(width: 24, height: 24),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["fish", "ocean", "orange", "plain"],
            version: 1
        )
    }()

    static let bugs: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "light_green", name: "Light Green", hex: "#90EE90"), PaletteColor(id: "black", name: "Black", hex: "#000000")]
        let rows: [String] = ["1111111111111111111111", "1111111111111111111111", "1111111111111111111111", "1111111112222111111111", "1111111122222211111111", "1111111122222211111111", "1111111022222201111111", "1111110022222200111111", "1111100002222000011111", "1111000220200220001111", "1111000220200220001111", "1111000000200000001111", "1111000000200000001111", "1111000020200200001111", "1111000220200220001111", "1111100020200200011111", "1111110000200000111111", "1111110000200000111111", "1111111100200011111111", "1111111111111111111111", "1111111111111111111111", "1111111111111111111111"]
        return FusePattern(
            id: "bugs-c2dc40cb-d80b-5d46-8d8b-4cd87d7c8b98", title: "Ladybug 1",
            category: .bugs, createdBy: .system,
            grid: GridSize(width: 22, height: 22),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["ladybug", "bug"],
            version: 1
        )
    }()

    static let food: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "cream", name: "Cream", hex: "#FFFDD0"), PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "green", name: "Green", hex: "#2E8B57"), PaletteColor(id: "brown", name: "Brown", hex: "#8B5E3C")]
        let rows: [String] = ["0000000000000000000000", "0000000000000000000000", "0000000000000000000000", "0000000000300200000000", "0000000000322000000000", "0000000000300000000000", "0000000000300000000000", "0000001111111111000000", "0000011111111111110000", "0000111111111111110000", "0000111111111111111000", "0000111111111111111000", "0000111111111111111000", "0000111111111111111000", "0000111111111111110000", "0000011111111111110000", "0000001111111111100000", "0000000000000000000000", "0000000000000000000000", "0000000000000000000000", "0000000000000000000000", "0000000000000000000000"]
        return FusePattern(
            id: "food-246c48ef-5d1e-53cb-b2d0-17f8ef8c6b60", title: "Apple 1",
            category: .food, createdBy: .system,
            grid: GridSize(width: 22, height: 22),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["food", "fruit", "apple"],
            version: 1
        )
    }()

    static let sweets: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "hot_pink", name: "Hot Pink", hex: "#FF1493"), PaletteColor(id: "light_blue", name: "Light Blue", hex: "#87CEEB"), PaletteColor(id: "brown", name: "Brown", hex: "#8B5E3C"), PaletteColor(id: "caramel", name: "Caramel", hex: "#C68642")]
        let rows: [String] = ["2222222222222222222222", "2222222222222222222222", "2222222222222222222222", "2222222222222222222222", "2222222222222222222222", "2222222221001222222222", "2222222111001112222222", "2222222111111112222222", "2222221111111111222222", "2222221111111111222222", "2222221111111111222222", "2222221111111111222222", "2222223111111112222222", "2222223411111142222222", "2222222344344342222222", "2222222344344342222222", "2222222344344342222222", "2222222234434432222222", "2222222232232232222222", "2222222222222222222222", "2222222222222222222222", "2222222222222222222222"]
        return FusePattern(
            id: "sweets-dedf58cb-e732-55de-8e11-234c02223e89", title: "Cupcake 1",
            category: .sweets, createdBy: .system,
            grid: GridSize(width: 22, height: 22),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["sweet", "dessert", "cupcake"],
            version: 1
        )
    }()

    static let trees: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "light_blue", name: "Light Blue", hex: "#87CEEB"), PaletteColor(id: "green", name: "Green", hex: "#2E8B57"), PaletteColor(id: "brown", name: "Brown", hex: "#8B5E3C")]
        let rows: [String] = ["00000000000000000000000000", "00000000000000000000000000", "00000000000000000000000000", "00000000000000000000000000", "00000000011111111000000000", "00000000111111111100000000", "00000001111111111110000000", "00000011111111111111000000", "00000011111111111111000000", "00000111111111111111100000", "00000111111111111111100000", "00000111111111111111100000", "00000111111111111111100000", "00000111111111111111100000", "00000011111111111111000000", "00000011111111111111000000", "00000001111111111110000000", "00000000111111111100000000", "00000000001111110000000000", "00000000002222200000000000", "00000000002222200000000000", "00000000002222200000000000", "00000000002222200000000000", "00000000002222200000000000", "00000000000000000000000000", "00000000000000000000000000"]
        return FusePattern(
            id: "trees-89ae0945-ee4b-5431-b839-4931c2e6bf20", title: "Tree 1",
            category: .trees, createdBy: .system,
            grid: GridSize(width: 26, height: 26),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["plant", "tree", "tree"],
            version: 1
        )
    }()

    static let vehicles: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "light_blue", name: "Light Blue", hex: "#87CEEB"), PaletteColor(id: "sky_blue", name: "Sky Blue", hex: "#5BC8F5"), PaletteColor(id: "dark_gray", name: "Dark Gray", hex: "#444444")]
        let rows: [String] = ["111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111112222222111111111", "111111112222222011111111", "111111112222222011111111", "111000002222222000001111", "111000000000000000001111", "111000000000000000001111", "111000030000000030001111", "111003333000000333301111", "111113333111111333311111", "111111333111111333111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111"]
        return FusePattern(
            id: "vehicles-5eb5cf93-f3d4-59fa-b623-2cb223b520c4", title: "Car 1",
            category: .vehicles, createdBy: .system,
            grid: GridSize(width: 24, height: 24),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["vehicle", "car"],
            version: 1
        )
    }()

    static let snowflakes: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "white", name: "White", hex: "#FFFFFF"), PaletteColor(id: "navy", name: "Navy", hex: "#001F5B")]
        let rows: [String] = ["111111111111010111111111111", "111111111110000011111111111", "111111111110000011111111111", "111111111110000011111111111", "111111111110101011111111111", "110000111100000001111000011", "110100011110101011110001011", "100000000100000001000000001", "100100100000101000001001001", "110001000101000101000100011", "111000010101101101010000111", "111100001001000100100001111", "111110000010010010000011111", "111111100110111011001111111", "111110000010010010000011111", "111100001001000100100001111", "111000010101101101010000111", "110001000101000101000100011", "100100100000101000001001001", "100000000100000001000000001", "110100011110101011110001011", "110000111100000001111000011", "111111111110101011111111111", "111111111110000011111111111", "111111111110000011111111111", "111111111110000011111111111", "111111111111010111111111111"]
        return FusePattern(
            id: "snowflakes-0004f98e-39aa-5a61-9c82-66030d23aa60", title: "Snowflake 1",
            category: .snowflakes, createdBy: .system,
            grid: GridSize(width: 27, height: 27),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["snowflake", "crystal", "6fold", "snowflakes"],
            version: 1
        )
    }()

    static let holidays: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "yellow", name: "Yellow", hex: "#F5D000"), PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "hot_pink", name: "Hot Pink", hex: "#FF1493"), PaletteColor(id: "light_blue", name: "Light Blue", hex: "#87CEEB"), PaletteColor(id: "sky_blue", name: "Sky Blue", hex: "#5BC8F5"), PaletteColor(id: "dark_green", name: "Dark Green", hex: "#006400"), PaletteColor(id: "brown", name: "Brown", hex: "#8B5E3C")]
        let rows: [String] = ["33333333333333333333333333", "33333333333333333333333333", "33333333333333333333333333", "33333333333300333333333333", "33333333333300333333333333", "33333333333555533333333333", "33333333335555553333333333", "33333333355555555333333333", "33333335555555555553333333", "33333355555555555555333333", "33333333333355322333333333", "33333333333555222333333333", "33333333311155522333333333", "33333333311155555333333333", "33333333555555555533333333", "33333335555544555553333333", "33333333333344333333333333", "33333333330005533333333333", "33333333330005533333333333", "33333333335055553333333333", "33333333355555555333333333", "33333333336666633333333333", "33333333336666633333333333", "33333333336666633333333333", "33333333333333333333333333", "33333333333333333333333333"]
        return FusePattern(
            id: "holidays-1dadbedb-246d-5596-a290-19f4c614af67", title: "Christmas Tree 1",
            category: .holidays, createdBy: .system,
            grid: GridSize(width: 26, height: 26),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["holiday", "xmastree"],
            version: 1
        )
    }()

    static let videogame: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "white", name: "White", hex: "#FFFFFF"), PaletteColor(id: "red", name: "Red", hex: "#CC1122"), PaletteColor(id: "navy", name: "Navy", hex: "#001F5B")]
        let rows: [String] = ["222222222222222222222222", "222222222222222222222222", "222222222222222222222222", "222222222222222222222222", "222222222111111222222222", "222222221111111122222222", "222222211111111112222222", "222222111111111111222222", "222222111111111111222222", "222221110001100011122222", "222211110021102211122222", "222211110021102211122222", "222211111111111111122222", "222211111111111111122222", "222211111111111111122222", "222211111111111111122222", "222211111111111111122222", "222221112111111211122222", "222222222222222222222222", "222222222222222222222222", "222222222222222222222222", "222222222222222222222222", "222222222222222222222222", "222222222222222222222222"]
        return FusePattern(
            id: "videogame-3672458d-2419-5c81-bb96-bd7f00d9fb5d", title: "Ghost 1",
            category: .videogame, createdBy: .system,
            grid: GridSize(width: 24, height: 24),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["game", "retro", "ghost"],
            version: 1
        )
    }()

    static let sports: FusePattern = {
        let palette: [PaletteColor] = [PaletteColor(id: "white", name: "White", hex: "#FFFFFF"), PaletteColor(id: "light_green", name: "Light Green", hex: "#90EE90"), PaletteColor(id: "black", name: "Black", hex: "#000000"), PaletteColor(id: "dark_gray", name: "Dark Gray", hex: "#444444")]
        let rows: [String] = ["111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111133331111111111", "111111113300003311111111", "111111130002200031111111", "111111300000000003111111", "111113000000000000311111", "111113200000000002311111", "111130220002200022031111", "111130000022220000031111", "111130000022220000031111", "111130000022220000031111", "111113000000000000311111", "111113002000000200311111", "111111302200002203111111", "111111130000000031111111", "111111113300003311111111", "111111111133331111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111", "111111111111111111111111"]
        return FusePattern(
            id: "sports-ed7e68fd-5afc-50d2-a525-8ab3816efea6", title: "Soccer Ball 1",
            category: .sports, createdBy: .system,
            grid: GridSize(width: 24, height: 24),
            palette: palette,
            cells: FusePattern.expand(rows: rows, palette: palette),
            difficulty: .hard, tags: ["sport", "soccer"],
            version: 1
        )
    }()

    static let all: [FusePattern] = [tile, mandala, heart, star, flower, rainbow, rocket, smiley, gem, letter, animals, birds, fish, bugs, food, sweets, trees, vehicles, snowflakes, holidays, videogame, sports]
}
